name: Continuous Deployment of SAM CFS Twitter Bot 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: apex/actions/aws/sam@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: build --use-container
      - name: Package
        uses: apex/actions/aws/sam@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: package --s3-bucket callforspeakerstwitterbot --output-template-file out.yaml
      - name: Deploy
        uses: apex/actions/aws/sam@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: deploy --template-file out.yaml --stack-name CallForSpeakersStack --capabilities CAPABILITY_NAMED_IAM

