name: Continuous Deployment of Lambda
on:
  push:
    branches:
      - master

jobs:
  deploy-lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Print AWS CLI version
        run: aws --version
      - name: Test Creds
        run: aws s3 ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
