name: Continuous Deployment of SAM CFS Twitter Bot 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: apex/actions/aws/sam@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: build
      - name: Package
        uses: apex/actions/aws/sam@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: package --s3-bucket callforspeakerstwitterbot
      - name: Deploy
        uses: apex/actions/aws/sam@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-west-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: deploy --stack-name CallForSpeakersStack --capabilities CAPABILITY_IAM --template-file
            out.yml

#      - name: Package CFS Twitter Bot
#        run: aws cloudformation package --template-file template.yaml --region us-east-1 --s3-bucket redactedtech
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: Deploy CFS Twitter Bot  
#        run: aws cloudformation deploy --template-file template.yaml --stack-name CallForSpeakersStack
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

