name: Continuous Deployment of SAM CFS Twitter Bot 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install AWS SAM CLI 
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
          sam --version
#      - name: Build
#        uses: r3dact3d/actions/aws/sam@hotfix/pip_import_error
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        with:
#          args: build
#      - name: Package CFS Twitter Bot
#        run: aws cloudformation package --template-file CallForSpeakersTemplate.yaml --region us-east-1 --s3-bucket redactedtech
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: Deploy CFS Twitter Bot  
#        run: aws cloudformation deploy --template-file CallForSpeakersTemplate.yaml --stack-name CallForSpeakersStack
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
