name: Continuous Deployment of SAM CFS Twitter Bot 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Homebrew 
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
          test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
          test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
          test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
          echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
          brew --version
      - name: Setup AWS SAM CLI 
        run: |
          brew tap aws/tap
          brew install aws-sam-cli
          sam --version

