name: Continuous Deployment of Lambda
on:
  push:
    branches:
      - master

jobs:
  deploy-lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Build CFS Twitter Bot SAM
        run: sam --version
        uses: apex/actions/aws/sam@master
      - name: List working dir
        run: pwd
      - name: Package CFS Twitter Bot
        run: aws cloudformation package --template-file CallForSpeakersTemplate.yaml --region us-east-1 --s3-bucket redactedtech
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy CFS Twitter Bot  
        run: aws cloudformation deploy --template-file CallForSpeakersTemplate.yaml --stack-name CallForSpeakersStack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
